name: faye_dart
description: Faye is a publish/subscribe messaging protocol that is built on the Bayeux protocol, a messaging system utilized for transporting asynchronous messages over HTTP.
version: 0.1.1+3
homepage: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
repository: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  logging: ^1.1.1
  meta: ^1.8.0
  uuid: ^4.2.1
  web_socket_channel: ^3.0.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.23.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
