name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 0.8.1
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.8.0
  rxdart: ^0.28.0
  stream_feed:
    #path: ../stream_feed
    git:
      url: https://github.com/rlee1990/stream-feed-flutter.git
      ref: master
      path: packages/stream_feed
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
